name: maven build & test
on:
  push:
    branches:
      - main
      - feature*
      - fix*
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #clone the repo
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build
        run: mvn -B package --file pom.xml
  test:
    runs-on: ubuntu-latest
    steps:
      #clone the repo
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Test
        run: mvn --batch-mode clean test